### ISSUE TITLE
train.pth wc=0

### ISSUE THREAD

**Issue by hcwu1993** [JavisPeng/ecg_pytorch#1]
Nice work. I have trouble with the code.  After I ran the script 'python data_process.py', i started train the model. But i found when i use torch.load() to load the tran.pth file, the wc array became 0.
![image](https://user-images.githubusercontent.com/19743635/65381408-3be57c80-dd23-11e9-93f4-3e1ba6e02e6d.png)
the other file seems normal. please give some advices, thanks!

**Comment by JavisPeng** [comment]
@hcwu1993 How strange, the 'file2idx' seems normal, I just downloaded the code and run the script 'python data_process.py' again, I got  a result of 'wc':
```python
.txt': [17, 5], '44291.txt': [0, 5], '44293.txt': [2, 5], '44294.txt': [0, 5], '44295.txt': [0, 5], '44296.txt': [0, 5], '44297.txt': [0, 5], '44298.txt': [17, 5], '44299.txt': [0, 5], '44301.txt': [0, 22, 5], '44302.txt': [0, 5], '44303.txt': [0, 22, 5], '44304.txt': [0, 5, 1], '44305.txt': [2, 5]}, 'wc': array([13974,  2841,  2869,  2473,  3754,  3894,  1097,  1703,  1485,
         183,  1273,   975,   923,  1063,   918,   826,   999,   800,
         266,   351,   213,   201,   169,    94,    72,    89,    61,
          68,    50,    53,    42,    36,    32,    29,    29,    34,
          24,    28,    24,    25,    21,    21,    25,    13,    14,
          18,    17,    14,    12,     8,    18,    14,    12,    18,
          16])}
```
This is my data directory:
```shell
-rw-rw-r-- 1 javis default_os_group       993 Sep  8 20:13 hf_round1_arrythmia.txt
-rw-rw-r-- 1 javis default_os_group   1239354 Sep  8 20:13 hf_round1_label.txt
-rw-rw-r-- 1 javis default_os_group    152815 Sep  8 20:13 hf_round1_subA.txt
drwxrwxr-x 3 javis default_os_group        27 Sep 10 09:27 hf_round1_testA
-rw-rw-r-- 1 javis default_os_group 287417240 Sep  8 20:14 hf_round1_testA.zip
drwxrwxr-x 3 javis default_os_group        27 Sep  8 21:21 hf_round1_train
-rw-rw-r-- 1 javis default_os_group 870982761 Sep  8 20:14 hf_round1_train.zip
```
wc is the count of each class, which get from the function, maybe you need to check it.
```python
wc=count_labels(train,file2idx)

def count_labels(data, file2idx):
    '''
    统计每个类别的样本数
    :param data:
    :param file2idx:
    :return:
    '''
    cc = [0] * config.num_classes
    for fp in data:
        for i in file2idx[fp]:
            cc[i] += 1
    return np.array(cc)
```

**Comment by hcwu1993** [comment]
Thank you. it's ok now. I generate the data again. Maybe i make a mistake when i copy the data to the project. The code ran on cpu. It' quiet snow on a i5 CPU ):.

**Comment by hcwu1993** [comment]
I want get some free GPU source. Do you have any idea?

**Comment by hcwu1993** [comment]
1.不太了解心电信号的处理， 为什么要对心电信号重采样，还有一些数据增强操作，可以解释下吗？
2. 代码中好像没有考虑性别与年龄，这两个特征对于预测结果应该是有帮助的
英文交流太麻烦了，直接中文了

**Comment by JavisPeng** [comment]
@hcwu1993 
1.我试过使用5000维度的数据，比较消耗GPU且训练比较慢，resample类似图片的resize，你也可以不resample，至于数据增强部分，是为了防止过拟合，参考于https://github.com/terryum/Data-Augmentation-For-Wearable-Sensor-Data
2.年龄和性别部分，最近工作有点忙，后续我也会考虑作为一个特征融合到模型中去

**Comment by hcwu1993** [comment]
谢谢
