### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by yuyell1996** [JavisPeng/ecg_pytorch#10]
您好！最近刚开始接触这个方向，想尝试运行一下您的代码，但是比赛官网的数据集现在已经无法下载，可以麻烦问一下您还有什么途径可以下载吗？

**Comment by JavisPeng** [comment]
之前的讨论里面有下载地址：
https://github.com/JavisPeng/ecg_pytorch/issues/5

**Comment by LiuXD1011** [comment]
> 之前的讨论里面有下载地址： #5

下载地址过期了，呜呜，可以发我一份不？谢谢您！我的电子邮箱是
2996628181@qq.com
