### ISSUE TITLE
能不能上传下数据

### ISSUE THREAD

**Issue by busyyang** [JavisPeng/ecg_pytorch#5]
现在天池已经不能下载数据了，能不能上传下数据，哪怕上传到百度网盘也行。

**Comment by JavisPeng** [comment]
@busyyang 由于版权问题，下载地址我就没有列到readme里面了：https://pan.baidu.com/s/1AdvvSzek-QTCSmvKcTEJDQ 提取码：ssue

**Comment by charlesfufu** [comment]
> @busyyang 由于版权问题，下载地址我就没有列到readme里面了：https://pan.baidu.com/s/1AdvvSzek-QTCSmvKcTEJDQ 提取码：ssue

云盘里面并没有label数据啊

**Comment by JavisPeng** [comment]
@charlesfufu 不好意思可能忘记上传了，我把所有的label都上传了，标签对应的数据，可以参考下天池的描述页面

**Comment by Studyingintheroad** [comment]
大佬能给小白一份数据吗 shuze_han@163.com  您发的百度网盘链接过期了
