### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by godzzbboss** [JavisPeng/ecg_pytorch#8]
你好，请问有完整的数据集吗？想自己练习下

**Comment by JavisPeng** [comment]
can you leave a email ?

**Comment by godzzbboss** [comment]
我的邮箱gao_he@nuaa.edu.cn,&nbsp; 多谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JavisPeng/ecg_pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月1日(星期六) 下午3:57
收件人:&nbsp;"JavisPeng/ecg_pytorch"<ecg_pytorch@noreply.github.com&gt;;
抄送:&nbsp;"1027785756"<1027785756@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [JavisPeng/ecg_pytorch] 数据集 (#8)





 
can you leave a email ?

**Comment by cdcx18** [comment]
please also send me the full datasets. thanks a lot.
email: cdcx01@sina.com

**Comment by Kaze-wind** [comment]
Could you also send me a copy of the datasets? Thanks.
Email. tlf@mail.ustc.edu.cn

**Comment by Dbassqwer** [comment]
> 你可以留下电子邮件吗？

作者你好，还能麻烦分享下数据集吗？谢谢啦。adzhang20@fudan.edu.cn

**Comment by zlfeng83** [comment]
Could you also send me a copy of the datasets? Much appreciated.
Email: steven83@126.com

**Comment by guowenqin2011** [comment]
您好，我想用数据集训练一下，能否把数据集发给我一份，我的电子邮箱是guowenqin2011@outlook.com，不胜感激。

**Comment by Theironflash** [comment]
您好，我想用数据集训练学习一下，可以发我一份吗？我的电子邮箱是227815491@qq.com

**Comment by LSQii** [comment]
Hello, could you also send me a copy of the datasets? Thanks a lot!  Email: 1435390664@qq.com

**Comment by Theironflash** [comment]
Sorry, I haven't received it either. If you get the datasets, please send me a copy. Thank you.


---原始邮件---
发件人: "LSQii"<notifications@github.com&gt;
发送时间: 2020年12月15日(周二) 晚上8:41
收件人: "JavisPeng/ecg_pytorch"<ecg_pytorch@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Theironflash"<2278154911@qq.com&gt;;
主题: Re: [JavisPeng/ecg_pytorch] 数据集 (#8)




 
Hello, could you also send me a copy of the datasets? Thanks a lot!  Email: 1435390664@qq.com

**Comment by guowenqin2011** [comment]
链接:https://pan.baidu.com/s/1AdvvSzek-QTCSmvKcTEJDQ提取码:ssue

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Theironflash** [comment]
万分感谢



---原始邮件---
发件人: "guowenqin2011"<notifications@github.com&gt;
发送时间: 2020年12月16日(周三) 上午7:45
收件人: "JavisPeng/ecg_pytorch"<ecg_pytorch@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Theironflash"<2278154911@qq.com&gt;;
主题: Re: [JavisPeng/ecg_pytorch] 数据集 (#8)




 链接:https://pan.baidu.com/s/1AdvvSzek-QTCSmvKcTEJDQ提取码:ssue 
 
 获取 Outlook for Android<https://aka.ms/ghei36&gt; 
 
 ________________________________

**Comment by WangXing-xx** [comment]
楼主您好，可以给我发train.pth这个文件，谢谢你了

**Comment by WangXing-xx** [comment]
楼主您好，可以给我发一下那个train.pth文件么，谢谢你了，我的邮箱2579520181@qq.comqq.com

**Comment by WangXing-xx** [comment]
楼主您好，可以给我发一下那个train.pth文件么，谢谢你了，我的邮箱2579520181@qq.com

**Comment by JavisPeng** [comment]
@WangXing-xx  这个文件记录了图片的路径，是由脚本data_process.py 生成

**Comment by LiuXD1011** [comment]
您好，我想用数据集训练学习一下，可以发我一份不？谢谢您！我的电子邮箱是
2996628181@qq.com

**Comment by godzzbboss** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
