### ISSUE TITLE
Request for relevant data of ecg_pytorch

### ISSUE THREAD

**Issue by JoaquinXu** [JavisPeng/ecg_pytorch#9]
Mr. JavisPeng:
       Hope you are doing well. I am a master's student in China and my research topic is related to deep learning and time-series data. Fortunately, I find your valuable project, so I downloaded your clone and attempted to run it. But it didn't work well as lacking some data files, such as 'hf_round1_label.txt', 'hf_round1_arrythmia.txt' etc. I entered the link you attached at README and registered an account in AliCloud, but it showed the data is only available for the participants. Therefore, could I ask for the complete data? If it is convenient for you, could you please send it to my email x774893095@163.com? Waiting for your reply.
Sincerely,
Joaquin Xu

**Comment by JavisPeng** [comment]
I have sent the download link by email

**Comment by JavisPeng** [comment]
@JoaquinXuI have sent the download link by email

**Comment by JoaquinXu** [comment]
Respectful:
Thanks for sending me the entire dataset, I implemented the codes by myself and got the idea of your work. Here, I have a question. In your program, the training loss was calculated by '(loss * self.weights).mean()', the 'self.weights' consists of 55 numbers which is equal to the class number. And it directly comes from the file 'train.pth'. I wonder how the weights calculated, could you please share me the idea?
Sincerely,
yours.
